### ISSUE TITLE
Build CLI

### ISSUE THREAD

**Issue by Macr0Nerd** [Macr0Nerd/EZ-DND#10]
**Is your feature request related to a problem? Please describe.**
Ima build a CLI

**Describe the solution you'd like**
GUIs are for Post-Alpha applications

**Describe alternatives you've considered**
Qt5, wxWidgets, GTKMM, all too complicated for one week

**Comment by RonaldHarding** [comment]
I like the idea of a CLI as well, not just as a pre-alpha feature for testing, but for long term support. As a DM, I could see myself using a well constructed CLI to interact with the game data much more efficiently than I could imagine hitting UI elements.

**Comment by Macr0Nerd** [comment]
Hi @RonaldHarding thank you for your feedback! The main purpose of the CLI was an attempt at something coherent before the Alpha, but I realized I was out of my depth with certain things.

However it is a feature I really do want, and it will be much easier than implementing a GUI so this is one of the things I’m going to work on for the next release. Thanks for your feedback!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
