### ISSUE TITLE
Improve Initial Build Experience

### ISSUE THREAD

**Issue by axlan** [Macr0Nerd/EZ-DND#11]
I am trying to build this project in Ubuntu 18.04, and hit a series of hurdles in getting the build going.

First it would be nice to add a more explicit instructions on setting up the library dependencies and running the build commands.

```
sudo apt-get build-essential
sudo apt-get install cmake
sudo apt-get install libpoco-dev
mkdir EZ-DND/build
cd EZ-DND/builld
cmake ..
make
```
Or whatever the preferred or tested methods are. Even if these are going to be somewhat OS specific having at least one working example gives people more to go on.

Second, following these steps I had build problems because the cmake version checks were too restrictive. Ubuntu 18.04 repos have:
```
cmake version 3.10.2
poco version 1.8.0
```
These seem to work fine, so I'm not sure if the version checks can be loosened or are required for future features.

Lastly after removing the version restrictions I got the following error:
```
Scanning dependencies of target ezdnd
[ 25%] Building CXX object CMakeFiles/ezdnd.dir/main.cpp.o
In file included from /home/jonathan/src/EZ-DND/main.cpp:3:0:
/home/jonathan/src/EZ-DND/src/Core/network.hpp:13:10: fatal error: filesystem: No such file or directory #include <filesystem>
```
filesystem was fully added in c++17 which isn't fully supported in GCC 7.4.0 that I'm using. There was experimental support which I got working.

I had to switch the include and namespaces to:
`#include <experimental/filesystem>`
and 
`std::experimental::filesystem::recursive_directory_iterator`

and change `target_link_libraries` to:
`target_link_libraries(ezdnd PUBLIC Poco::Foundation Poco::Net stdc++fs)`

There's probably a way to check for this at compile time and give a more informative error that a newer compiler is needed, or to fall back on another method for iterating over files in a directory.

Listing a specific OS and release and giving explicit instructions for installing the libraries would help people avoid these issues as well.

**Comment by Macr0Nerd** [comment]
Hi! Thank you for your feedback! So these are some really great comments and I really appreciate your feedback. I’ll get on all of these ASAP. Thank you again! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Macr0Nerd** [comment]
So after taking my sabbatical, I've returned and will hop on this immediately. I will be setting stuff up for this, but just a word or warning, the network class will be deprecated soon as I realize how much of a mistake I was making by not just doing networking and logic with the UI (such as Qt supporting networking)

**Comment by Macr0Nerd** [comment]
I'm going with the nuclear option and requiring C++17. I believe that gcc 7.4 does report it as CMAKE_CXX_STANDARD 17 so just incase i still include the stdc++fs in the linked libraries. Thank you for bringing this too my attention!
