### ISSUE TITLE
Documented Fair Use

### ISSUE THREAD

**Issue by RonaldHarding** [Macr0Nerd/EZ-DND#12]
It would be a good idea to come up with a set of guidelines and add them to the documentation regarding the kind of content that can be used in this project. Using DnD in the name is already pushing it and I'd be concerned to contribute to a project that without proper controls could easily someday co-opt game rules, text, or images from copyrighted published works.

**Comment by Macr0Nerd** [comment]
@RonaldHarding just as D&D is meant to be built upon, this project follows that. While I can’t include official copyrighted content, the D&D 5e SRD is already somewhat implemented and legal to use. I am concerned about having D&D in the name, but should it become an issue, I am ready to change it.

And it also needs to be able to be built on so people can implement their own changes and do things like add weapons, armor, classes, and the such.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
