### ISSUE TITLE
Build base GUI

### ISSUE THREAD

**Issue by Macr0Nerd** [Macr0Nerd/EZ-DND#9]
I reallllllllly don't want to, but it feels like I should. Please don't make me.

**Comment by Macr0Nerd** [comment]
I'm terrible at front end. Someone please take over

**Comment by RonaldHarding** [comment]
Are there any kind of requirements for this? This project is still very early on and needs some direction before we just start going off on our own direction architecting core components that will have an impact on everything that happens in the future. Might want to set up a discord for discussion.

**Comment by Macr0Nerd** [comment]
@RonaldHarding So the main features that I want would want would essentially just be a P2P board manager. Obviously I have board and characters classes set up for use and would want those to be used for portability between any provided option. More so the character class as I plan on building a character manager to go along with a GUI

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Macr0Nerd** [comment]
I hate this. I hate it so much. It's going to be terrible and I can't design for shit.

That being said, I'll set up Qt5 in the morning.
